### ISSUE TITLE
Jess is making a commit to /website, but she got denied permission. Can we edit this repo?

### ISSUE THREAD

**Issue by 94kazakov** [challengerapp/website#1]

**Comment by AlJaMa** [comment]
On it!

**Comment by AlJaMa** [comment]
should be resolved now. Please close issue if so. If not, comment

**Comment by 94kazakov** [comment]
awesome! Works now!

**Comment by AlJaMa** [comment]
Note: this is a fantastic way to get ahold of me ASAP. Github issues bubble to the top of my inbox.
